version: "2"
run:
  timeout: 5m
formatters:
  enable:
    - gofmt
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errorlint
    - errchkjson
    - exhaustive
    - forcetypeassert
    - gochecknoglobals
    - goconst
    - gocritic
    # - goerr113
    - goprintffuncname
    - gosec
    - grouper
    - ireturn
    - loggercheck
    - makezero
    - mirror
    - misspell
    # - musttag
    - nakedret
    # - nestif
    - nilerr
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    # - varnamelen
    - wastedassign
    - whitespace

  settings:
    revive:
      rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported
        - name: exported
          severity: warning
          disabled: false
          # arguments:
          #   - "preserveScope"
          #   - "checkPrivateReceivers"
          #   - "sayRepetitiveInsteadOfStutters"
issues:
  max-issues-per-linter: 50
  max-same-issues: 0
  # include:
  #   - EXC0011
  #   - EXC0012
  #   - EXC0013
  #   - EXC0014
  #   - EXC0015
