ARG VERSION
FROM ghcr.io/crumbhole/argocd-lovely-plugin-cmp:${VERSION} as source
FROM alpine:3.17.1
COPY --from=source /argocd-lovely-plugin .
USER 999
ENTRYPOINT [ "cp", "argocd-lovely-plugin", "/custom-tools/" ]
