kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
apiVersion: v1
data:
  ui.bannercontent: "Security Goose says: This is eks-runner. Should you be here? HONK!"
  statusbadge.enabled: "true"
  ui.bannerpermanent: "true"

  configManagementPlugins: |-
    - name: argocd-vault-replacer
      generate:
        command: ["argocd-vault-replacer"]
    - name: kustomize-argocd-vault-replacer
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . | argocd-vault-replacer"]
    - name: helm-argocd-vault-replacer
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template -n $ARGOCD_APP_NAMESPACE $ARGOCD_APP_NAME . | argocd-vault-replacer"]
    - name: helm-kustomize
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template -n $ARGOCD_APP_NAMESPACE $ARGOCD_APP_NAME $HELM_ARGS . > all.yaml && kustomize build | argocd-vault-replacer"]
    - name: argocd-lovely-plugin
      init:
        command: ["argocd-lovely-plugin"]
        args: ["init"]
      generate:
        command: ["argocd-lovely-plugin"]
  resource.compareoptions: |
    ignoreResourceStatusField: all
  resource.customizations: |
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
  # The metadata.label key name where Argo CD injects the app name as a tracking label (optional).
  # Tracking labels are used to determine which resources need to be deleted when pruning.
  # If omitted, Argo CD injects the app name into the label: 'app.kubernetes.io/instance'
  application.instanceLabelKey: pipekit.io/appname