name: Variations
description: Build variations of lovely
inputs:
  version:
    description: 'Version to build'
    required: true
runs:
  using: "composite"
  steps:
    - name: Build and Push argocd-lovely-plugin
      uses: docker/build-push-action@v4
      with:
        context: .
        file: variations/Dockerfile.legacy
        push: true
        platforms: ${{ env.PLATFORMS }}
        tags: ghcr.io/crumbhole/argocd-lovely-plugin:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=ghcr.io/crumbhole/argocd-lovely-plugin-cmp
    - name: Build and Push lovely
      uses: docker/build-push-action@v4
      with:
        context: .
        file: variations/Dockerfile.nover
        push: true
        platforms: ${{ env.PLATFORMS }}
        tags: ghcr.io/crumbhole/lovely:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=ghcr.io/crumbhole/argocd-lovely-plugin-cmp
    - name: Build and Push lovely-vault-ver
      uses: docker/build-push-action@v4
      with:
        context: .
        file: variations/Dockerfile.vault
        push: true
        platforms: ${{ env.PLATFORMS }}
        tags: ghcr.io/crumbhole/lovely-vault-ver:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=ghcr.io/crumbhole/argocd-lovely-plugin-cmp
    - name: Build and Push lovely-vault
      uses: docker/build-push-action@v4
      with:
        context: .
        file: variations/Dockerfile.nover
        push: true
        platforms: ${{ env.PLATFORMS }}
        tags: ghcr.io/crumbhole/lovely-vault:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=ghcr.io/crumbhole/lovely-vault-ver
    - name: Build and Push lovely-vault-plugin-ver
      uses: docker/build-push-action@v4
      with:
        context: .
        file: variations/Dockerfile.vault-plugin
        push: true
        platforms: ${{ env.PLATFORMS }}
        tags: ghcr.io/crumbhole/lovely-vault-plugin-ver:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=ghcr.io/crumbhole/argocd-lovely-plugin-cmp
    - name: Build and Push lovely-vault-plugin
      uses: docker/build-push-action@v4
      with:
        context: .
        file: variations/Dockerfile.nover
        push: true
        platforms: ${{ env.PLATFORMS }}
        tags: ghcr.io/crumbhole/lovely-vault-plugin:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=ghcr.io/crumbhole/argocd-lovely-plugin-cmp
    - name: Build and Push lovely-hera-ver
      uses: docker/build-push-action@v4
      with:
        context: .
        file: variations/Dockerfile.hera
        push: true
        platforms: ${{ env.PLATFORMS }}
        tags: ghcr.io/crumbhole/lovely-hera-ver:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=ghcr.io/crumbhole/argocd-lovely-plugin-cmp
    - name: Build and Push lovely-hera
      uses: docker/build-push-action@v4
      with:
        context: .
        file: variations/Dockerfile.nover
        push: true
        platforms: ${{ env.PLATFORMS }}
        tags: ghcr.io/crumbhole/lovely-hera:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=ghcr.io/crumbhole/lovely-hera-ver
    - name: Build and Push lovely-hera-vault-ver
      uses: docker/build-push-action@v4
      with:
        context: .
        file: variations/Dockerfile.vault
        push: true
        platforms: ${{ env.PLATFORMS }}
        tags: ghcr.io/crumbhole/lovely-hera-vault-ver:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=ghcr.io/crumbhole/lovely-hera-ver
    - name: Build and Push lovely-hera-vault
      uses: docker/build-push-action@v4
      with:
        context: .
        file: variations/Dockerfile.nover
        push: true
        platforms: ${{ env.PLATFORMS }}
        tags: ghcr.io/crumbhole/lovely-hera-vault:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=ghcr.io/crumbhole/lovely-hera-vault-ver
    - name: Build and Push lovely-hera-vault-plugin-ver
      uses: docker/build-push-action@v4
      with:
        context: .
        file: variations/Dockerfile.vault-plugin
        push: true
        platforms: ${{ env.PLATFORMS }}
        tags: ghcr.io/crumbhole/lovely-hera-vault-plugin-ver:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=ghcr.io/crumbhole/lovely-hera-ver
    - name: Build and Push lovely-hera-vault-plugin
      uses: docker/build-push-action@v4
      with:
        context: .
        file: variations/Dockerfile.nover
        push: true
        platforms: ${{ env.PLATFORMS }}
        tags: ghcr.io/crumbhole/lovely-hera-vault-plugin:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=ghcr.io/crumbhole/lovely-hera-vault-plugin-ver
