name: Variations
description: Build variations of lovely
inputs:
  version:
    description: 'Version to build'
    required: true
  push:
    description: 'Push images to registry'
    required: false
    default: 'true'
  registry:
    description: 'Registry prefix for images (e.g., ghcr.io/crumbhole or localhost:5000)'
    required: false
    default: 'ghcr.io/crumbhole'
runs:
  using: "composite"
  steps:
    - name: Build and Push lovely
      uses: docker/build-push-action@v6
      with:
        context: .
        file: variations/Dockerfile.nover
        push: ${{ inputs.push }}
        platforms: ${{ env.PLATFORMS }}
        tags: ${{ inputs.registry }}/lovely:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=${{ inputs.registry }}/argocd-lovely-plugin-cmp
          NAME=lovely
    - name: Build and Push lovely-vault-ver
      uses: docker/build-push-action@v6
      with:
        context: .
        file: variations/Dockerfile.vault
        push: ${{ inputs.push }}
        platforms: ${{ env.PLATFORMS }}
        tags: ${{ inputs.registry }}/lovely-vault-ver:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=${{ inputs.registry }}/argocd-lovely-plugin-cmp
          NAME=lovely-vault-ver
    - name: Build and Push lovely-vault
      uses: docker/build-push-action@v6
      with:
        context: .
        file: variations/Dockerfile.nover
        push: ${{ inputs.push }}
        platforms: ${{ env.PLATFORMS }}
        tags: ${{ inputs.registry }}/lovely-vault:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=${{ inputs.registry }}/lovely-vault-ver
          NAME=lovely-vault
    - name: Build and Push lovely-vault-plugin-ver
      uses: docker/build-push-action@v6
      with:
        context: .
        file: variations/Dockerfile.vault-plugin
        push: ${{ inputs.push }}
        platforms: ${{ env.PLATFORMS }}
        tags: ${{ inputs.registry }}/lovely-vault-plugin-ver:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=${{ inputs.registry }}/argocd-lovely-plugin-cmp
          NAME=lovely-vault-plugin-ver
    - name: Build and Push lovely-vault-plugin
      uses: docker/build-push-action@v6
      with:
        context: .
        file: variations/Dockerfile.nover
        push: ${{ inputs.push }}
        platforms: ${{ env.PLATFORMS }}
        tags: ${{ inputs.registry }}/lovely-vault-plugin:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=${{ inputs.registry }}/lovely-vault-plugin-ver
          NAME=lovely-vault-plugin
    - name: Build and Push lovely-hera-ver
      uses: docker/build-push-action@v6
      with:
        context: .
        file: variations/Dockerfile.hera
        push: ${{ inputs.push }}
        platforms: ${{ env.PLATFORMS }}
        tags: ${{ inputs.registry }}/lovely-hera-ver:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=${{ inputs.registry }}/argocd-lovely-plugin-cmp
          NAME=lovely-hera-ver
    - name: Build and Push lovely-hera
      uses: docker/build-push-action@v6
      with:
        context: .
        file: variations/Dockerfile.nover
        push: ${{ inputs.push }}
        platforms: ${{ env.PLATFORMS }}
        tags: ${{ inputs.registry }}/lovely-hera:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=${{ inputs.registry }}/lovely-hera-ver
          NAME=lovely-hera
    - name: Build and Push lovely-hera-vault-ver
      uses: docker/build-push-action@v6
      with:
        context: .
        file: variations/Dockerfile.vault
        push: ${{ inputs.push }}
        platforms: ${{ env.PLATFORMS }}
        tags: ${{ inputs.registry }}/lovely-hera-vault-ver:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=${{ inputs.registry }}/lovely-hera-ver
          NAME=lovely-hera-vault-ver
    - name: Build and Push lovely-hera-vault
      uses: docker/build-push-action@v6
      with:
        context: .
        file: variations/Dockerfile.nover
        push: ${{ inputs.push }}
        platforms: ${{ env.PLATFORMS }}
        tags: ${{ inputs.registry }}/lovely-hera-vault:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=${{ inputs.registry }}/lovely-hera-vault-ver
          NAME=lovely-hera-vault
    - name: Build and Push lovely-hera-vault-plugin-ver
      uses: docker/build-push-action@v6
      with:
        context: .
        file: variations/Dockerfile.vault-plugin
        push: ${{ inputs.push }}
        platforms: ${{ env.PLATFORMS }}
        tags: ${{ inputs.registry }}/lovely-hera-vault-plugin-ver:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=${{ inputs.registry }}/lovely-hera-ver
          NAME=lovely-hera-vault-plugin-ver
    - name: Build and Push lovely-hera-vault-plugin
      uses: docker/build-push-action@v6
      with:
        context: .
        file: variations/Dockerfile.nover
        push: ${{ inputs.push }}
        platforms: ${{ env.PLATFORMS }}
        tags: ${{ inputs.registry }}/lovely-hera-vault-plugin:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=${{ inputs.registry }}/lovely-hera-vault-plugin-ver
          NAME=lovely-hera-vault-plugin
    - name: Build and Push lovely-ytt-ver
      uses: docker/build-push-action@v6
      with:
        context: .
        file: variations/Dockerfile.ytt
        push: ${{ inputs.push }}
        platforms: ${{ env.PLATFORMS }}
        tags: ${{ inputs.registry }}/lovely-ytt-ver:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=${{ inputs.registry }}/argocd-lovely-plugin-cmp
          NAME=lovely-ytt-ver
    - name: Build and Push lovely-ytt
      uses: docker/build-push-action@v6
      with:
        context: .
        file: variations/Dockerfile.nover
        push: ${{ inputs.push }}
        platforms: ${{ env.PLATFORMS }}
        tags: ${{ inputs.registry }}/lovely-ytt:${{ inputs.version }}
        build-args: |
          VERSION=${{ inputs.version }}
          PARENT=${{ inputs.registry }}/lovely-ytt-ver
          NAME=lovely-ytt
