ARG VERSION
ARG PARENT
FROM ${PARENT}:${VERSION}
ARG NAME
ENV PLUGIN_NAME="${NAME}"
ENV LOVELY_PREPROCESSORS="python3 *.py"
ENV LOVELY_DETECTION_REGEX="\.py$"
USER 0
RUN apk add --update --no-cache python3
RUN python3 -m ensurepip
RUN pip3 install hera[yaml]
USER 999
