ARG VERSION
ARG PARENT
FROM ${PARENT}:${VERSION}
ARG NAME
USER 0
RUN yq -i e ".metadata.name |= \"${NAME}\"" /home/argocd/cmp-server/config/plugin.yaml
USER 999
ENV LOVELY_PLUGINS=argocd-vault-replacer
COPY --from=ghcr.io/crumbhole/argocd-vault-replacer:0.11.10 /argocd-vault-replacer /usr/local/bin/argocd-vault-replacer
