ARG VERSION
ARG PARENT
FROM ${PARENT}:${VERSION}
ARG NAME
USER 0
RUN yq -i e ".metadata.name |= \"${NAME}\"" /home/argocd/cmp-server/config/plugin.yaml
ENV LOVELY_PREPROCESSORS="python3 *.py"
ENV LOVELY_DETECTION_REGEX="\.py$"
RUN apk add --update --no-cache python3
RUN python3 -m ensurepip
RUN pip3 install hera[yaml]
USER 999
