ARG VERSION
ARG PARENT
FROM ${PARENT}:${VERSION}
ARG NAME
USER 0
RUN yq -i e ".metadata.name |= \"${NAME}\"" /home/argocd/cmp-server/config/plugin.yaml
RUN yq -i 'del(.spec.version)' /home/argocd/cmp-server/config/plugin.yaml
USER 999
