name: Code Check
description: Check the code is up to date
runs:
  using: "composite"
  steps:
  - name: Set up Go
    uses: actions/setup-go@v4
    with:
      go-version-file: 'go.mod'

  - name: Code check
    run: make -j code-check
