apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-plus-additions
  namespace: argocd
spec:
  destination:
    namespace: helm-plus-additions
    server: 'https://kubernetes.default.svc'
  source:
    path: examples/kustomize-helm/manifests
    repoURL: 'https://github.com/crumbhole/argocd-lovely-plugin.git'
    targetRevision: HEAD
    plugin:
      name: argocd-lovely-plugin
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=background
      - CreateNamespace=true