name: Build and test

on:
  push:
    branches: [ main ]

jobs:
  gogitops:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: GoGitOps Step
      id: gogitops
      uses: beaujr/gogitops-action@v0.2
      with:
        github-actions-token: ${{secrets.GITHUB_TOKEN}}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Get
      run: go get -v ./...
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          tags: ghcr.io/crumbhole/argocd-lovely-plugin:latest
